{{- $chart := .Chart -}}
{{- $values := .Values -}}
{{- range $node := $values.nvidia.metropolis.nodes }}
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ $chart.Name }}-{{ $node.name | replace "." "-" }}
spec:
  limits:
  - default:
{{- with $node.resources.limits }}
{{ toYaml . | indent 8 }}
{{- end }}
    defaultRequest:
{{- with $node.resources.requests }}
{{ toYaml . | indent 8 }}
{{- end }}
    type: Container
---
{{- end }}
