# Default values for myco-hello.
# This is a YAML-formatted file.
# NOTE: Only one container can use auto for numGpu

pods:
- name: hello
  replicas: 1
  initContainers:
  - name: hello-init
    image: "centos:7"
    command: ["/bin/sh", "-c"]
    args:
    - |
      cd $HTML_ROOT;
      echo hello > index.html;
    env:
    - name: HTML_ROOT
      value: "/mnt/html"
    volumeMounts:
    - name: hello-pvc
      subPath: html
      mountPath: /mnt/html
  containers:
  - name: hello
#    image: "nvcr.io/myco/hello:2.0.0"
    image: "centos:7"
    command: ["/bin/sh", "-c"]
    args:
    - |
      cd $HTML_ROOT;
      python -m SimpleHTTPServer 80;
    env:
    - name: HTML_ROOT
      value: "/mnt/html"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: hello-pvc
      subPath: html
      mountPath: /mnt/html
      readOnly: true
    metropolis:
      useNvidiaDevicePlugin: yes
      numGpu: auto
  volumes:
  - name: hello-pvc
    persistentVolumeClaim:
      claimName: hello-pvc
      metropolis:
        storageType: slow
        storageSize: 100Mi
  service:
#    type: NodePort
    type: ClusterIP
    ports:
    - name: http
      port: 80
      targetPort: 80
#      nodePort: 30080


# Below Values will be overriden by NVIDIA Metropolis Portal
# Below should be an example for 1 stream to include in your Helm Chart
# An operator will be asked to customize the hostnames, GPU IDs and streams information
# GPU IDs are PCI BUS order

nvidia:
  version: 1
  metropolis:
    nodes:
    - name: "sc-metro-03"
      gpus:
      - id: 0
        streams:
        - url: “rtsp://”
          resolution: “1920 x 1080”
          framerate: 30
          encoding: “H264”
      resources:
        requests:
          cpu: "100m"
          memory: "10Mi"
        limits:
          cpu: "120m"
          memory: "12Mi"

global:
  nvidia:
    version: 1
    docker:
      registry: "nvcr.io"
      username: "$oauthtoken"
      password: "secret"
    storageClassName:
      slow: local-path
      fast: local-path

