# Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

{{- $release := .Release -}}
{{- $chart := .Chart -}}
{{- $values := .Values -}}
{{- $files := .Files -}}
{{- range $node := $values.nvidia.nodes }}
{{- range $pod := $values.pods }}
{{- range $configMap := $pod.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    app: {{ $chart.Name }}
    app.version: {{ $chart.AppVersion }}
  labels:
    name: {{ $configMap.name }}
    app.kubernetes.io/instance: {{ $release.Name }}
  name: {{ $configMap.name }}
  namespace: {{ $chart.Name }}-{{ $node.name | replace "." "-" }}
data:
{{- range $data := $configMap.dataFromFile }}
  {{ $data.name }}: {{ $files.Get $data.source | quote }}
{{- end }}
{{- range $data := $configMap.dataFromValueAsText }}
{{- range $key, $val := $values }}
{{- if eq $key $data.source }}
  {{ $data.name }}: {{ $val | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- range $data := $configMap.dataFromValueAsYaml }}
{{- range $key, $val := $values }}
{{- if eq $key $data.source }}
  {{ $data.name }}: {{ toYaml $val | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- with $configMap.data }}
{{ toYaml . | indent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
